import img from '../../assets/img/slider1.jpg';

const Json = [
  {
    img: img,
    title: 'title',
    text: 'lorem ipsum lorem ipsum lorem ipsum',
    students: 100,
    categories: 1,
    price: '15$',
    teacher: {
      job: 'teacher',
      rank: 5,
      name: 'John',
      lastName: 'LastName',
      img: img,
    },
    courseRank: 80,
    link: 'https://preview.colorlib.com/#webuni',
  },
  {
    img: img,
    title: 'title2',
    text: 'lorem22 222 ipsum lorem ipsum lorem ipsum',
    students: 110,
    categories: 1,
    price: '15$',
    teacher: {
      job: 'developer',
      rank: 5,
      name: 'Nil',
      lastName: 'LastName', img: img,

    },
    courseRank: 90,
    link: 'https://preview.colorlib.com/#webuni',
  },
  {
    img: img,
    title: 'title',
    text: 'lorem ipsum lorem ipsum lorem ipsum',
    students: 100,
    categories: 1,
    price: '15$',
    teacher: {
      job: 'teacher',
      rank: 5,
      name: 'John',
      lastName: 'LastName',
      img: img,
    },
    courseRank: 80,
    link: 'https://preview.colorlib.com/#webuni',
  },
  {
    img: img,
    title: 'title2',
    text: 'lorem22 222 ipsum lorem ipsum lorem ipsum',
    students: 110,
    categories: 1,
    price: '15$',
    teacher: {
      job: 'developer',
      rank: 5,
      name: 'Nil',
      lastName: 'LastName', img: img,

    },
    courseRank: 90,
    link: 'https://preview.colorlib.com/#webuni',
  },
  {
    img: img,
    title: 'title',
    text: 'lorem ipsum lorem ipsum lorem ipsum',
    students: 100,
    categories: 1,
    price: '15$',
    teacher: {
      job: 'teacher',
      rank: 5,
      name: 'John',
      lastName: 'LastName',
      img: img,
    },
    courseRank: 80,
    link: 'https://preview.colorlib.com/#webuni',
  },
  {
    img: img,
    title: 'title2',
    text: 'lorem22 222 ipsum lorem ipsum lorem ipsum',
    students: 110,
    categories: 1,
    price: '15$',
    teacher: {
      job: 'developer',
      rank: 5,
      name: 'Nil',
      lastName: 'LastName', img: img,

    },
    courseRank: 90,
    link: 'https://preview.colorlib.com/#webuni',
  },
  {
    img: img,
    title: 'title',
    text: 'lorem ipsum lorem ipsum lorem ipsum',
    students: 100,
    categories: 1,
    price: '15$',
    teacher: {
      job: 'teacher',
      rank: 5,
      name: 'John',
      lastName: 'LastName',
      img: img,
    },
    courseRank: 80,
    link: 'https://preview.colorlib.com/#webuni',
  },
  {
    img: img,
    title: 'title2',
    text: 'lorem22 222 ipsum lorem ipsum lorem ipsum',
    students: 110,
    categories: 1,
    price: '15$',
    teacher: {
      job: 'developer',
      rank: 5,
      name: 'Nil',
      lastName: 'LastName', img: img,

    },
    courseRank: 90,
    link: 'https://preview.colorlib.com/#webuni',
  },
  {
    img: img,
    title: 'title',
    text: 'lorem ipsum lorem ipsum lorem ipsum',
    students: 100,
    categories: 1,
    price: '15$',
    teacher: {
      job: 'teacher',
      rank: 5,
      name: 'John',
      lastName: 'LastName',
      img: img,
    },
    courseRank: 80,
    link: 'https://preview.colorlib.com/#webuni',
  },
  {
    img: img,
    title: 'title2',
    text: 'lorem22 222 ipsum lorem ipsum lorem ipsum',
    students: 110,
    categories: 1,
    price: '15$',
    teacher: {
      job: 'developer',
      rank: 5,
      name: 'Nil',
      lastName: 'LastName', img: img,

    },
    courseRank: 90,
    link: 'https://preview.colorlib.com/#webuni',
  },
  {
    img: img,
    title: 'title',
    text: 'lorem ipsum lorem ipsum lorem ipsum',
    students: 100,
    categories: 1,
    price: '15$',
    teacher: {
      job: 'teacher',
      rank: 5,
      name: 'John',
      lastName: 'LastName',
      img: img,
    },
    courseRank: 80,
    link: 'https://preview.colorlib.com/#webuni',
  },
  {
    img: img,
    title: 'title2',
    text: 'lorem22 222 ipsum lorem ipsum lorem ipsum',
    students: 110,
    categories: 1,
    price: '15$',
    teacher: {
      job: 'developer',
      rank: 5,
      name: 'Nil',
      lastName: 'LastName', img: img,

    },
    courseRank: 90,
    link: 'https://preview.colorlib.com/#webuni',
  },
  {
    img: img,
    title: 'title',
    text: 'lorem ipsum lorem ipsum lorem ipsum',
    students: 100,
    categories: 1,
    price: '15$',
    teacher: {
      job: 'teacher',
      rank: 5,
      name: 'John',
      lastName: 'LastName',
      img: img,
    },
    courseRank: 80,
    link: 'https://preview.colorlib.com/#webuni',
  },
  {
    img: img,
    title: 'title2',
    text: 'lorem22 222 ipsum lorem ipsum lorem ipsum',
    students: 110,
    categories: 1,
    price: '15$',
    teacher: {
      job: 'developer',
      rank: 5,
      name: 'Nil',
      lastName: 'LastName', img: img,

    },
    courseRank: 90,
    link: 'https://preview.colorlib.com/#webuni',
  },


];

export default Json;